# =============================================================
# docker/compose.dev.yml
# TuChati Development Stack
# Extends main compose.yml for local development
# Adds live-reloading frontend (Vite) + backend mounts
# =============================================================

services:
  # --------------------------------------------
  # 🌍 Django Backend (Development)
  # --------------------------------------------
  web:
    env_file:
      - ../.env.dev  # Optional: redundant with symlink, but explicit
    volumes:
      - ../backend:/app/backend
      - ../frontend:/app/frontend
      - ../locale:/app/locale
    ports:
      - "8011:8000"
    # Inherits depends_on and healthcheck from compose.yml
    # Enables live reload via volume mounts

  # --------------------------------------------
  # 💻 Frontend (React + Vite)
  # --------------------------------------------
  frontend:
    image: node:20-alpine
    working_dir: /app/frontend/web
    volumes:
      - ../frontend/web:/app/frontend/web
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true  # enables live reload in Docker
    depends_on:
      - web
