# docker/compose.dev.yml
services:
  web:
    env_file:
      - ../.env.dev
    volumes:
      - ../backend:/app/backend
      - ../frontend:/app/frontend
      - ../locale:/app/locale
    ports:
      - "8011:8000"

  db:
    env_file:
      - ../.env.dev

  redis:
    env_file:
      - ../.env.dev

  nginx:
    env_file:
      - ../.env.dev
