# docker/compose.dev.yml
services:
  web:
    env_file:
      - ../.env.dev  # Optional: Redundant with symlink, but keeps explicit
    volumes:
      - ../backend:/app/backend
      - ../frontend:/app/frontend
      - ../locale:/app/locale
    ports:
      - "8011:8000"
    # Inherits depends_on/healthcheck from compose.yml