name: tuchati
services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6389:6379"

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - ./.env
    working_dir: /app/backend
    command: ["/entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - staticdata:/app/staticfiles
      - mediadata:/app/media
    expose:
      - "8000"

  frontend:
    image: node:20-alpine
    working_dir: /app/frontend/web
    volumes:
      - ../frontend/web:/app/frontend/web
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - web
    restart: always

  nginx:
    image: nginx:1.27-alpine
    restart: always
    depends_on:
      - web
      - frontend
    env_file:
      - ./.env
    expose:
      - "80"
    ports:
      - "8092:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - staticdata:/staticfiles:ro
      - mediadata:/media:ro

volumes:
  db_data:
  staticdata:
  mediadata:
