# =============================================================
# docker/compose.dev.yml
# TuChati Development Stack
# Extends main compose.yml for local development
# Adds live-reloading frontend (Vite) + backend mounts
# =============================================================

  # --------------------------------------------
  # Django Backend (Development)
  # --------------------------------------------
services:
  web:
    env_file: [ ../.env.dev ]
    volumes:
      - ../backend:/app/backend
      - ../locale:/app/locale
    ports:
      - "8011:8000"

  # --------------------------------------------
  # 💻 Frontend (React + Vite)
  # --------------------------------------------
  # Vite dev server in dev only
  frontend:
    image: node:20-alpine
    working_dir: /app/frontend/web
    volumes:
      - ../frontend/web:/app/frontend/web
    command: sh -lc "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - web