#Dockerfile.nginx
# =======================
# --- build frontend ---
FROM node:20-alpine AS frontend-builder
WORKDIR /app/frontend/web
COPY frontend/web/package*.json ./
RUN npm ci
COPY frontend/web ./
# pass Vite envs at build time 
RUN npm run build

# --- runtime nginx with static files ---
FROM nginx:1.27-alpine
COPY docker/nginx/conf.d/app.conf /etc/nginx/conf.d/default.conf
# copy built files
COPY --from=frontend-builder /app/frontend/web/build /usr/share/nginx/html
