# Generated by Django 5.2.7 on 2025-10-08 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_remove_user_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesession',
            name='app_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='devicesession',
            name='connection_status',
            field=models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='devicesession',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
