# Generated by Django 5.2.7 on 2025-10-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailverificationcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='accounts_em_email_b45245_idx',
            old_name='accounts_em_email__2b246a_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationcode',
            new_name='accounts_em_user_id_1ba8bf_idx',
            old_name='accounts_em_user_id_91f01a_idx',
        ),
    ]
