# Generated by Django 5.2.7 on 2025-10-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_pinned_by_messageusermeta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messageusermeta',
            new_name='chat_messag_user_id_3969b1_idx',
            old_name='chat_msgmeta_user_starred_idx',
        ),
        migrations.RenameIndex(
            model_name='messageusermeta',
            new_name='chat_messag_message_9e5aa3_idx',
            old_name='chat_msgmeta_msg_deleted_idx',
        ),
    ]
