# Generated by Django 5.2.7 on 2025-10-15 22:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_directchatrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directchatrequest',
            name='unique_direct_request_status',
        ),
        migrations.AlterUniqueTogether(
            name='directchatrequest',
            unique_together={('from_user', 'to_user', 'status')},
        ),
    ]
