# Generated by Django 5.2.7 on 2025-10-19 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_groupinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupinvite',
            name='unique_group_invite_status',
        ),
        migrations.RenameIndex(
            model_name='groupinvite',
            new_name='chat_groupi_invitee_dc11c7_idx',
            old_name='chat_group_invitee_status_idx',
        ),
        migrations.RenameIndex(
            model_name='groupinvite',
            new_name='chat_groupi_inviter_3a3625_idx',
            old_name='chat_group_inviter_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together={('room', 'invitee', 'status')},
        ),
    ]
