# Generated by Django 5.2.7 on 2025-10-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_default_roles'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='adminpanel__event_t_84b869_idx',
            old_name='adminpanel_event_ty_bb8c69_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='adminpanel__severit_0c013c_idx',
            old_name='adminpanel_severity_919597_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='adminpanel__created_1b33d3_idx',
            old_name='adminpanel_created__2e3f0c_idx',
        ),
    ]
